name: sandbox
services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:v2.54.1
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=4GB"
      - "--storage.tsdb.retention.time=120d"
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  prometheus-data:
  grafana-data:
