global:
  evaluation_interval: 15s

scrape_configs:
  - job_name: "http_server"
    scrape_interval: 1s
    static_configs:
      - targets:
          - "172.18.0.1:8000"
  - job_name: "grpc_server"
    scrape_interval: 1s
    static_configs:
      - targets:
          - "172.18.0.1:12346"
